### ISSUE TITLE
新买的m1 mac无法使用订阅，也无法连接服务器

### ISSUE THREAD

**Issue by RuoxuZhang** [jack80342/ShadowsocksX-NG#7]
新买的m1 macbook pro，

1）使用订阅地址后点击手动更新没有反应，
2）连接自己搭的服务器也不能科学上网，
3）使用小猴子客户端连接ssr和v2ray节点也不能科学上网，

上述这些方式用我的windows是可以上网的，但新买的macbook不行，请问是什么原因？

**Comment by jack80342** [comment]
有日志吗？

**Comment by eromoe** [comment]
我打都打不开。 是直接解压就能运行吗，在隐私权限里也允许运行了，角标闪一下就没了

**Comment by jack80342** [comment]
> 我打都打不开。 是直接解压就能运行吗，在隐私权限里也允许运行了，但是角标闪一下就没了

M1是ARM架构的，还没有适配

**Comment by jun58** [comment]
> > 我打都打不开。 是直接解压就能运行吗，在隐私权限里也允许运行了，但是角标闪一下就没了
> 
> 还没有适配M1

我的就是最新的M1，是不是压缩包解压然后点小飞机就可以了，还是我说的问题，打开之后baidu都打不开了
日志报这个错
![image](https://user-images.githubusercontent.com/20509429/123631029-d94ed800-d848-11eb-99ff-45294a792244.png)
我已经brew下载了这个了
![image](https://user-images.githubusercontent.com/20509429/123631142-fc798780-d848-11eb-8f97-7e4422965bd5.png)
搞了好久了，头疼

**Comment by Austin-Young-Pro** [comment]
我也是M1用不了，希望快快适配吧！

**Comment by jack80342** [comment]
> 我也是M1用不了，希望快快适配吧！

适配好了
https://github.com/jack80342/ShadowsocksX-NG-R/releases/tag/v1.6.5

**Comment by jack80342** [comment]
> 我也是M1用不了，希望快快适配吧！

手里没有M1的苹果电脑，只是打包了通用应用，目前应该没有完全适配

**Comment by jack80342** [comment]
已适配。
